### ISSUE TITLE
Errors with scraper.py?

### ISSUE THREAD

**Issue by notsureofagoodname** [Syps/alexa-airplane-spotter#1]
Hi There, thanks for putting this together. I'm very close to having it working based on a lot of hard work of yours. It's very cool and I'm looking forward to getting it going. I've overcome a few little install issues, but can't seem to figure out this one.

server.js is successfully invoking nearby.py which is calling scraper.py I get the below Python Traceback when a plane is found. When no planes are found, the node.js remains up correctly.

EG Plane/URL being located; **url=https://www.flightradar24.com/data/aircraft/VH-EBD** 

```
----- Python Traceback -----
    File "live_speech_output.py", line 40, in <module>
      get_output_speech()
    File "live_speech_output.py", line 30, in get_output_speech
      flight = nearby()
    File "/home/pi/alexa-airplane-spotter/nearby.py", line 171, in nearby
      return scrape.flight_info(flight) if flight else None
    File "/home/pi/alexa-airplane-spotter/scrape.py", line 108, in flight_info
      route_results = scrape_route_data(reg_no)
    File "/home/pi/alexa-airplane-spotter/scrape.py", line 64, in scrape_route_data
      depart = route_row.findAll('td')[2].find('span').text
user@raspberrypi:/home/pi/alexa-airplane-spotter$ python nearby.py
Traceback (most recent call last):
  File "nearby.py", line 175, in <module>
    nearby()
  File "nearby.py", line 171, in nearby
    return scrape.flight_info(flight) if flight else None
  File "/home/pi/alexa-airplane-spotter/scrape.py", line 107, in flight_info
    route_results = scrape_route_data(reg_no)
  File "/home/pi/alexa-airplane-spotter/scrape.py", line 63, in scrape_route_data
    depart = route_row.findAll('td')[2].find('span').text
AttributeError: 'NoneType' object has no attribute 'findAll'
```

route_row is returning None, meaning route_row.findAll is bombing. The URL being access, as seen via logger.info (URL sample above), is correct and I can see the required tr/td info...

I might dig into this a little more, but am not feeling too confident on this. Greatly appreciate a hand on the scraping..

Unrelated, but whilst opening an issue, in the blog post I saw no mention of OpenSky or it's usage, which is still in the page and was a bit of a curveball, but no biggie.

Thanks again/in advance!

**Comment by notsureofagoodname** [comment]
Okay, so I've been poking around, have a feeling cloudflare's at fault here. I'm getting HTTP 418's (of all the error codes?!) back from them (on multiple computers!) using requests, yet, curl outside of python works fine...

```
>>> r = requests.get('https://www.flightradar24.com/data/aircraft/VH-EBD')
>>> r.status_code
418
>>> r.headers
{'Content-Length': '0', 'Set-Cookie': '__cfduid=da812b654c6ed2625c5ff3fda0a91be6d1499432798; expires=Sat, 07-Jul-18 13:06:38 GMT; path=/; domain=.flightradar24.com; HttpOnly', 'Server': 'cloudflare-nginx', 'Connection': 'keep-alive', 'Date': 'Fri, 07 Jul 2017 13:06:38 GMT', 'CF-RAY': '37ab05aebc606593-SYD'}
```

Changing the user agent in python to curl has moved this along
```
>>> headers = {'user-agent': 'curl/7.38.0'}
>>> r = requests.get('https://www.flightradar24.com/data/aircraft/VH-EBD', headers=headers)
>>> r.status_code
200
>>> r.headers
{'Content-Encoding': 'gzip', 'Transfer-Encoding': 'chunked', 'Set-Cookie': '__cfduid=df3d99751006b5c9c89ee77af133590f51499433031; expires=Sat, 07-Jul-18 13:10:31 GMT; path=/; domain=.flightradar24.com; HttpOnly, FR24ID=0vpp4u9vlsa8nlmh27fbqn2bqg96ki6ccqh04nbmfihi0ouq7o60; path=/', 'Expires': 'Fri, 07 Jul 2017 13:25:31 GMT', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare-nginx', 'Last-Modified': 'Fri, 07 Jul 2017 13:10:31 GMT', 'Connection': 'keep-alive', 'Pragma': 'cache', 'Cache-Control': 'max-age=900', 'Date': 'Fri, 07 Jul 2017 13:10:32 GMT', 'CF-RAY': '37ab0b5fcdb06569-SYD', 'Content-Type': 'text/html; charset=utf-8', 'X-Airport': 'TXL'}
```

The airport nearby has now closed, so I'll have to wait until tomorrow to test this out. Should be fine I think...Might be worth keeping in mind if it's a  CF thing...

**Comment by notsureofagoodname** [comment]
Yep, that fixed it, up and running after setting the headers; thanks!
[ 'That\'s a BLUE SKY HELICOPTERS BELL 206L going from Sydney to Bankstown' ]

**Comment by notsureofagoodname** [comment]
Just for completedness' sake this was committed/fixed in https://github.com/Syps/alexa-airplane-spotter/commit/39bcdad829495797598a89c87d5463dad3d60aaf
